version: 2

models:
  - name: stg_paysim
    description: "Cleaned staging model for PaySim transactions"

    columns:
      - name: step
        tests:
          - not_null

      - name: type
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

      - name: sender_account
        tests:
          - not_null

      - name: receiver_account
        tests:
          - not_null

      - name: is_fraud
        tests:
          - not_null

      - name: is_flagged_fraud
        tests:
          - not_null